#!/bin/bash
if [[ $_ == $0 ]] ; then
    echo "Error: This script needs to be sourced. Please run as 'source $0'"
    exit 1
fi
if [[ -n "$BUILDDIR" ]] ; then
        echo "Build environment already set."
	exit 1
else

PRN=$(basename $BASH_SOURCE)
PRD=$(readlink -f $(dirname $BASH_SOURCE))

echo "PRN=$PRN"
echo "PRD=$PRD"

if [[ -f $PRD/.templateconf ]] ; then
        source $PRD/.templateconf
fi
export TEMPLATECONF
echo "TEMPLATECONF=$TEMPLATECONF"

source $PRD/sources/poky/oe-init-build-env

fi
